# Generated by Django 3.1.3 on 2020-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
