# Generated by Django 3.1.3 on 2020-11-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOH', '0002_auto_20201111_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('emotion_score', models.IntegerField()),
                ('emotion_state', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
