# Generated by Django 3.1.3 on 2020-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOH', '0003_auto_20201118_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
